<?xml version='1.0'?>
<ns2:test-suite xmlns:ns2='urn:model.allure.qatools.yandex.ru' start='1689779317165' stop='1689779347476'>
    <name>Testing the Scenario 2 </name>
    <title>Testing the Scenario 2 </title>
    <test-cases>
        <test-case start='1689779317166' status='broken' stop='1689779347466'>
            <name>Testing Scenario 2</name>
            <title>Testing Scenario 2</title>
            <labels/>
            <parameters/>
            <steps/>
            <attachments/>
            <failure>
                <message>`cy.visit()` failed trying to load:
                
                http://localhost:3000/
                
                We attempted to make an http request to this URL but the request failed without a response.
                
                We received this error at the network level:
                
                  > Error: ESOCKETTIMEDOUT
                
                Common situations why this would fail:
                  - you don't have internet access
                  - you forgot to run / boot your web server
                  - your web server isn't accessible
                  - you have weird network configuration settings on your computer
                
                Because this error occurred during a `before each` hook we are skipping the remaining tests in the current suite: `Testing the Scenario 2 `</message>
                <stack-trace>CypressError: `cy.visit()` failed trying to load:
                
                http://localhost:3000/
                
                We attempted to make an http request to this URL but the request failed without a response.
                
                We received this error at the network level:
                
                  > Error: ESOCKETTIMEDOUT
                
                Common situations why this would fail:
                  - you don't have internet access
                  - you forgot to run / boot your web server
                  - your web server isn't accessible
                  - you have weird network configuration settings on your computer
                
                Because this error occurred during a `before each` hook we are skipping the remaining tests in the current suite: `Testing the Scenario 2 `
                    at http://localhost:57433/__cypress/runner/cypress_runner.js:157807:23
                    at visitFailedByErr (http://localhost:57433/__cypress/runner/cypress_runner.js:157162:12)
                    at http://localhost:57433/__cypress/runner/cypress_runner.js:157806:11
                    at tryCatcher (http://localhost:57433/__cypress/runner/cypress_runner.js:10325:23)
                    at Promise._settlePromiseFromHandler (http://localhost:57433/__cypress/runner/cypress_runner.js:8260:31)
                    at Promise._settlePromise (http://localhost:57433/__cypress/runner/cypress_runner.js:8317:18)
                    at Promise._settlePromise0 (http://localhost:57433/__cypress/runner/cypress_runner.js:8362:10)
                    at Promise._settlePromises (http://localhost:57433/__cypress/runner/cypress_runner.js:8438:18)
                    at _drainQueueStep (http://localhost:57433/__cypress/runner/cypress_runner.js:5032:12)
                    at _drainQueue (http://localhost:57433/__cypress/runner/cypress_runner.js:5025:9)
                    at ../../node_modules/bluebird/js/release/async.js.Async._drainQueues (http://localhost:57433/__cypress/runner/cypress_runner.js:5041:5)
                    at Async.drainQueues (http://localhost:57433/__cypress/runner/cypress_runner.js:4911:14)
                
                From Node.js Internals:
                  Error: ESOCKETTIMEDOUT
                      at ClientRequest.&lt;anonymous> (C:\Users\deepa\AppData\Local\Cypress\Cache\5.6.0\Cypress\resources\app\packages\server\node_modules\@cypress\request\request.js:816:19)
                      at Object.onceWrapper (events.js:416:28)
                      at ClientRequest.emit (events.js:310:20)
                      at Socket.emitRequestTimeout (_http_client.js:709:9)
                      at Object.onceWrapper (events.js:416:28)
                      at Socket.emit (events.js:322:22)
                      at Socket._onTimeout (net.js:479:8)
                      at listOnTimeout (internal/timers.js:549:17)
                      at processTimers (internal/timers.js:492:7)
                  </stack-trace>
            </failure>
        </test-case>
    </test-cases>
</ns2:test-suite>